public enum ActionType
{
    GIVE_CHLAMYDIA_ANTIBIOTICS,
    GIVE_GONNORHEA_ANTIBIOTICS,
    GIVE_INJECTION,
    GIVE_REPEAT_PRESCRIPTION,
    GIVE_BLOOD_TEST_KIT,
    GIVE_SWAB_TEST_KIT,
    GIVE_URINE_TEST_KIT,
    GIVE_CONDOMS,
    GIVE_ADVICE
};

public enum ActionEffectiveness
{
    WORST,
    BAD,
    NEUTRAL,
    GOOD,
    BEST
}